config/routes.rb
Rails.application.routes.draw do

  resources :blogs
  resources :passengers
  devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :agencies
  resources :tour_packages
  resources :tours
  resources :uploads
  resources :blogs
  resources :access_controls


  get '', to: 'home#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root "home#index"

  get 'settings/index'
  get "settings/sections" => "settings#sections"
  get '/settings', to: "settings#index"

  post '/airlines', to: "airlines#create"
  post '/railways', to: "railways#create"
  post '/buses', to: "buses#create"
  post '/hotels', to: "hotels#create"
  post '/price_types', to: "price_types#create"

  get '/uploads/remoted/:id', to: "uploads#remoted"
  get '/tour_packages/upload/:id', to: "tour_packages#upload"

  get '/railways/options', to: "railways#options"
  get '/airlines/options', to: "airlines#options"
  get '/buses/options', to: "buses#options"

  get '/reservations/new', to: "reservations#new"
  get '/reservations/passengers', to: "reservations#passengers"
  get '/reservations/verification', to: "reservations#verification"
  get '/reservations/:id/destroy', to: "reservations#destroy"
  get '/reservations/verify_reservations/:id', to: "reservations#verify_reservations"


  get '/tour_packages/check/:id', to: "tour_packages#check"
  get '/tour_packages/change_rank/:id', to: "tour_packages#change_rank"
  get '/tour_packages/change_status/:id', to: "tour_packages#change_status"

  get '/blogs/check/:id', to: "blogs#check"
  get '/blogs/change_rank/:id', to: "blogs#change_rank"

  get '/landing', to: "home#landing"

  post '/roles', to: "roles#create"
  get '/roles/:id/destroy', to: "roles#destroy"
  get '/roles/access/:id', to: "roles#access"
  get '/roles/change_current_role', to: "roles#change_current_role"

  post '/assignments', to: "assignments#create"
  get '/assignments/:id/destroy', to: "assignments#destroy"

  post '/provinces', to: "provinces#create"
  get '/provinces/:id/destroy', to: "provinces#destroy"

  get '/api/tour_packages', to: "api#tour_packages"
  get '/api/tour_package/:id', to: "api#tour_package"
  get '/api/tour/:id', to: "api#tour"
  get '/api/login', to: "api#login"
  get '/api/tour_reservations/:id', to: "api#tour_reservations"
  get '/api/delete_reservation/:id', to: "api#delete_reservation"
  get '/api/verify_reservation/:id', to: "api#verify_reservation"
  get '/api/verified_reservations/:id', to: "api#verified_reservations"
  get '/api/my_reservations', to: "api#my_reservations"
  get '/api/blogs', to: "api#blogs"
  get '/api/provinces', to: "api#provinces"
  get '/api/blog/:id', to: "api#blog"

  post '/api/sign_up', to: "api#sign_up"
  post '/api/reservation', to: "api#reservation"
end

app/models/tour_package.rb
class TourPackage < ActiveRecord::Base
  self.primary_key = 'uuid'
  after_save ThinkingSphinx::RealTime.callback_for(:tour_package)

  belongs_to :agency
  belongs_to :province

  has_many :tours, :dependent => :destroy
  has_many :uploads, :as => :uploadable, :dependent => :destroy

  def image(style)
    @upload = Upload.where(uploadable_type: 'TourPackage', uploadable_id: self.id, attachment_type: 'tour_package_attachment').first
    if !@upload.blank?
      return @upload.attachment(style)
    else
      ActionController::Base.helpers.asset_path("noimage-35-#{style}.jpg", :digest => false)
    end
  end

  def cover(style)
    @upload = Upload.where(uploadable_id: self.id, attachment_type: 'tour_package_attachment').first
    if !@upload.blank?
      return @upload.attachment(style)
    else
      ActionController::Base.helpers.asset_path("noimage-#{style}.png", :digest => false)
    end
  end

  before_create :set_integer_id
  def set_integer_id
    @last = TourPackage.all.order('integer_id desc').first
    if !@last.blank?
      @last_id = @last.integer_id
    else
      @last_id = 0
    end
    self.integer_id = @last_id + 1
  end

  before_create :set_rank
  def set_rank
    self.rank = 0
  end

  before_create :set_uuid
  def set_uuid
    self.uuid = SecureRandom.uuid
  end

  def id
    self.uuid
  end

  def self.find(uuid)
    TourPackage.find_by_uuid(uuid)
  end

end

app/controllers/tour_packages_controller.rb
class TourPackagesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_tour_package, only: [:show, :edit, :update, :destroy, :check, :change_rank, :change_status, :change_size]
  before_action :check_user, only: [:new, :edit, :update, :destroy, :create]
  before_action :verify_ads, only: [:change_status, :change_size, :check]

  def change_status
    if params[:status] == "1"
      @tour_package.status = 1
    else
      @tour_package.status = 0
    end
    @tour_package.save
  end

  def change_size
    if params[:size] == "2"
      @tour_package.size = 2
    else
      @tour_package.size = 1
    end
    @tour_package.save
  end

  def change_rank
    if !grant_access("ability_to_verify_ads", current_user)
      head(403)
    else
      if params[:move] == 'up'
        @tour_package.rank += 1
      else
        @tour_package.rank -= 1
      end
      @tour_package.save
      redirect_to '/'
    end
  end

  def check
    if params[:to] == 'check'
      @tour_package.view_in_homepage = true
    else
      @tour_package.view_in_homepage = false
    end
    @tour_package.save
  end

  def upload

  end
  # GET /tour_packages
  # GET /tour_packages.json
  def index
    @tour_packages = TourPackage.all
  end

  # GET /tour_packages/1
  # GET /tour_packages/1.json
  def show
  end

  # GET /tour_packages/new
  def new
    @tour_package = TourPackage.new
  end

  # GET /tour_packages/1/edit
  def edit
      @upload_ids = Upload.where(uploadable_type: 'TourPackage', uploadable_id: @tour_package.id).pluck(:id)
  end

  # POST /tour_packages
  # POST /tour_packages.json
  def create
    @tour_package = TourPackage.new(tour_package_params)
    @tour_package.agency_id = current_user.agency.id
    respond_to do |format|
      if @tour_package.save
        manage_uploads(@tour_package.id)
        format.html { redirect_to "/tour_packages/#{@tour_package.id}", notice: 'Tour package was successfully created.' }
        format.json { render :show, status: :created, location: @tour_package }
      else
        format.html { render :new }
        format.json { render json: @tour_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tour_packages/1
  # PATCH/PUT /tour_packages/1.json
  def update
    handle_chkbox
    respond_to do |format|
      if @tour_package.update(tour_package_params)
        if params['upload'].blank?
          format.html { redirect_to @tour_package, notice: 'Tour package was successfully updated.' }
        else
          format.html { redirect_to "/tour_packages", notice: 'Tour package was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @tour_package }
      else
        format.html { render :edit }
        format.json { render json: @tour_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_packages/1
  # DELETE /tour_packages/1.json
  def destroy
    @tour_package.destroy
    respond_to do |format|
      format.html { redirect_to tour_packages_url, notice: 'Tour package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tour_package
    @tour_package = TourPackage.find(params[:id])
  end

  def handle_chkbox
    @tour_package.father_name_field = false
    @tour_package.birthdate_field = false
    @tour_package.place_of_birth_field = false
    @tour_package.passport_no_field = false
    @tour_package.en_name_field = false
    @tour_package.en_surename_field = false
    @tour_package.en_father_name_field = false
    @tour_package.attachment_field = false
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tour_package_params
    params.require(:tour_package).permit(:title, :days, :nights, :details, :uuid, :father_name_field, :birthdate_field, :place_of_birth_field,:passport_no_field, :en_name_field,:en_surename_field, :en_father_name_field, :attachment_field, :attachment_message)
  end

  def verify_ads
    if !grant_access("ability_to_verify_ads", current_user)
      head(403)
    end
  end

  def check_user
    if !grant_access("ability_to_post_tour_packages", current_user)
      head(403)
    end
  end
end

app/helpers/tour_packages_helper.rb
module TourPackagesHelper
end

app/views/tour_packages/_form.html.erb
<%= form_for(@tour_package, html: {class: 'card'}) do |f| %>
<div class="card-header">
  <h3 class="card-title"><%=t :new_tour_package %></h3>
</div>
<% if @tour_package.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@tour_package.errors.count, "error") %> prohibited this tour_package from being saved:</h2>

  <ul>
    <% @tour_package.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="card-body">
  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :title, class: "form-label" %>
        <%= f.text_field :title , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :days, class: "form-label" %>
        <%= f.number_field :days , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :nights, class: "form-label" %>
        <%= f.number_field :nights , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.label :details, class: "form-label" %>
        <%= f.text_area :details , class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="form-label"><%=t :required_fields%></div>
    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="tour_package[father_name_field]" value="1"  <% if @tour_package.father_name_field%>checked=""<%end%>>
      <span class="custom-control-label"><%=t :father_name_field%></span>
    </label>

    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="tour_package[birthdate_field]" value="1"  <% if @tour_package.birthdate_field%>checked=""<%end%>>
      <span class="custom-control-label"><%=t :birthdate_field%></span>
    </label>

    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="tour_package[place_of_birth_field]" value="1"  <% if @tour_package.place_of_birth_field%>checked=""<%end%>>
      <span class="custom-control-label"><%=t :place_of_birth_field%></span>
    </label>

    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="tour_package[passport_no_field]" value="1"  <% if @tour_package.passport_no_field%>checked=""<%end%>>
      <span class="custom-control-label"><%=t :passport_no_field%></span>
    </label>

    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="tour_package[en_name_field]" value="1"  <% if @tour_package.en_name_field%>checked=""<%end%>>
      <span class="custom-control-label"><%=t :en_name_field%></span>
    </label>

    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="tour_package[en_surename_field]" value="1"  <% if @tour_package.en_surename_field%>checked=""<%end%>>
      <span class="custom-control-label"><%=t :en_surename_field%></span>
    </label>

    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="tour_package[en_father_name_field]" value="1"  <% if @tour_package.en_father_name_field%>checked=""<%end%>>
      <span class="custom-control-label"><%=t :en_father_name_field	%></span>
    </label>

    <label class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="tour_package[attachment_field]" value="1"  <% if @tour_package.attachment_field%>checked=""<%end%>>
      <span class="custom-control-label"><%=t :attachment_field	%></span>
    </label>

    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :attachment_message, class: "form-label" %>
          <%= f.text_area :attachment_message , class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <% if @upload_ids.blank?%>
  <%= hidden_field_tag :attachments, ''%>
  <%else%>
  <%= hidden_field_tag :attachments, @upload_ids.split(',')%>
  <%end%>
  <% end %>
  <h5 style="color:#24426c;"><i class="fa fa-paperclip" style="vertical-align:-2px;"></i> <%=t :pictures%></h5>
  <hr class="mt-2 mb-4"/>
  <% if @tour_package.id == nil%>
  <%= render partial: 'uploads/upload_form', locals: {id: '0', ratio: '1/1', class_name: 'TourPackage', type:'tour_package_attachment'}%>
  <%else%>
  <%= render partial: 'uploads/upload_form', locals: {id: @tour_package.id, ratio: '1/1', class_name: 'TourPackage', type:'tour_package_attachment'}%>
  <%end%>
  <div class="card-footer text-right">
    <button id='submit-btn' type="button" class="btn btn-primary"><%=t :submit%></button>
  </div>
  <script>
  $(document).ready(function(){
    $( "#submit-btn" ).one('click', function(event) {
      $( "#new_tour_package" ).submit();
    });
  });
  </script>
</div>

app/views/tour_packages/_tour_package_block.html.erb
<div class="card">
  <a href="/tour_packages/<%= tour_package.id%>"><img class="card-img-top" src="<%= tour_package.image('medium')%>" alt="<%= tour_package.title%>"></a>
  <div class="card-body d-flex flex-column">
    <h4><a href="#"><%= tour_package.title%></a></h4>
    <div class="text-muted"><%= truncate( tour_package.details, length: 70)%></div>
    <div class="d-flex align-items-center pt-5 mt-auto">
      <div class="ml-auto text-muted">
        <a href="javascript:void(0)" class="icon d-none d-md-inline-block ml-3"><i class="fe fe-heart mr-1"></i></a>
        <% if params[:controller] == 'home'%>
        <%= link_to "/tour_packages/change_rank/#{tour_package.id}?move=up" do%>
        <i class="fa fa-arrow-up"></i>
        <%end%>
        <%= link_to "/tour_packages/change_rank/#{tour_package.id}?move=down" do%>
        <i class="fa fa-arrow-down"></i>
        <%end%>
        <%end%>
      </div>

      <div>

        <small class="d-block text-muted"><%= tour_package.days%> <%=t :days%> <%=t :and%> <%= tour_package.nights%> <%=t :nights%></small>
      </div>

    </div>
  </div>
</div>

<% if params[:action] == 'show'%>
<div class="list-group list-group-transparent mb-4 text-center">
  <%= link_to @tour_package, class: "list-group-item list-group-item-action active small", style:'font-weight:normal;',  method: :delete, data: { confirm: 'Are you sure?' } do%>
  <i class="fe fe-trash" style="vertical-align:middle;"></i> <%=t :delete_this_package%>
  <%end%>
</div>
<div class="list-group list-group-transparent mb-4 text-center">
  <%= link_to "/tour_packages/#{@tour_package.id}/edit", class: "list-group-item list-group-item-action active small", style:'font-weight:normal;' do%>
  <i class="fe fe-edit" style="vertical-align:middle;"></i> <%=t :edit%>
  <%end%>
</div>
<%end%>

app/views/tour_packages/index.html.erb
<div class="row row-cards row-deck">
  <% for tour_package in @tour_packages%>
  <div class="col-sm-4 col-xl-3">
    <%= render partial: 'tour_packages/tour_package_block', locals: {tour_package: tour_package}%>
  </div>
  <%end%>
</div>

app/views/tour_packages/show.html.erb
<div class='row'>
  <div class="col-lg-4 order-lg-1">
    <%= render partial: 'tour_packages/tour_package_block', locals: {tour_package: @tour_package}%>
  </div>
  <div class="col-lg-8 order-lg-1">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"></h3>
        <div class="card-options">
          <label class="custom-switch ml-2 mt-1" style='float: left;'>
            <input type="checkbox" name="view_<%=@tour_package.id%>" id='view_<%= @tour_package.id%>' <%if @tour_package.view_in_homepage%>checked<%end%> class="custom-switch-input">
            <span class="custom-switch-indicator"></span>
            <span class="custom-switch-description" style='font-size: 80%;'><%=t :view_in_the_first_page%></span>
          </label>
          <script>
          $('.custom-switch-input').change(function() {
            var id = $(this).attr('id').split("_")[1];
            if($(this).is(":checked")) {
              $.ajax({
                url: '/tour_packages/check/'+id,
                type: 'GET',
                dataType: 'json',
                data: {
                  segment_id: id,
                  to: 'check'
                },
                error: function() {
                  $(this).attr("checked", false);
                },
                success: function(res) {
                  $(this).attr("checked", true);
                }
              });
            } else {
              $.ajax({
                url: '/tour_packages/check/'+id,
                type: 'GET',
                dataType: 'json',
                data: {
                  segment_id: id,
                  to: 'uncheck'
                },
                error: function() {
                  $(this).attr("checked", true);
                },
                success: function(res) {
                  $(this).attr("checked", false);
                }
              });
            }
          });
          </script>
          <%= link_to new_tour_path(tour_package_id: params[:id]), class:'btn btn-secondary' do%>
          <i class="fa fa-globe"></i> <%=t :new_tour%>
          <%end%>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-hover table-outline table-vcenter ">
          <thead>
            <tr>
              <td><%=t :departure%></td>
              <td><%=t :arrival%></td>
              <td><%=t :price_range%></td>
              <td><%=t :accomodation%></td>
              <td></td>
            </tr>
          </thead>
          <% for tour in @tour_package.tours%>
          <tr>
            <td>
              <div>
                <%= tour.jalali_start_date%>
              </div>
              <div class="small text-muted">
                <% @transportation = tour.transportations.where(leg: "Departure").order(:created_at).first%>
                <% if !@transportation.blank?%>
                <%=t @transportation.transportable_type.downcase.pluralize%>: <%= @transportation.transportable_type.classify.constantize.find(@transportation.transportable_id).name rescue nil%>
                <%end%>
              </div>
            </td>
            <td>
              <div>
                <%= tour.jalali_end_date%>
              </div>
              <div class="small text-muted">
                <% @transportation = tour.transportations.where(leg: "Arrival").order(:created_at).first%>
                <% if !@transportation.blank?%>
                <%=t @transportation.transportable_type.downcase.pluralize%>: <%= @transportation.transportable_type.classify.constantize.find(@transportation.transportable_id).name rescue nil%>
                <%end%>
              </div>
            </td>
            <td>
              <div style="white-space: nowrap;">
              <%@upper_price = tour.pricings.order('value desc').limit(2).first %>
              <% if !@upper_price.blank?%>
              <strong><%= @upper_price.value%></strong>
              <%end%>
              <%@down_price = tour.pricings.order('value desc').limit(2).last %>
              <% if !@down_price.blank? && !@down_price.value.blank?%>
              - <strong><%= @down_price.value%></strong>
              <%end%>
            </div>
            </td>
            <td>
              <%@accomodation1 = tour.accomodations.order('nights desc').limit(2).first %>
              <% if !@accomodation1.blank?%>
              <div class="small text-muted" style="white-space: nowrap;"><%= Hotel.find(@accomodation1.accomodable_id).name%>  <%=raw Hotel.find(@accomodation1.accomodable_id).star%></div>
              <%end%>
              <%@accomodation2 = tour.accomodations.order('nights desc').limit(2).last %>
              <% if !@accomodation1.blank? && @accomodation1 != @accomodation2%>
              <div class="small text-muted" style="white-space: nowrap;"><%= Hotel.find(@accomodation2.accomodable_id).name%> <%=raw Hotel.find(@accomodation2.accomodable_id).star%></div>
              <%end%>
            </td>
            <td class="text-right">
              <div style="white-space: nowrap;">
              <% if tour.remained_capacity > 0%>
                <%= link_to "/reservations/new?tour_id=#{tour.id}", class:'btn btn-sm btn-success' do%>
                  <i class="fe fe-plus-circle" style="vertical-align: -3px;"></i> <%=t :reservation%>
                <%end%>
              <%end%>
              <%= link_to "/tours/#{tour.uuid}", class:'btn btn-sm btn-secondary' do%>
              <i class="fe fe-play"></i><%=t :show%>
              <%end%>
            </div>
            </td>
          </tr>
          <%end%>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/tour_packages/upload.html.erb
<div class="card">
  <div class="card-body">
    <%= render partial: 'uploads/upload_form', locals: {id: params[:id], ratio: '4/3', class_name: 'TourPackage', type:'tour_package_attachment'}%>
  </div>
  <div class="card-footer text-right">
    <a href='/tour_packages/<%= @tour_package.id%>' class="btn btn-success"><%=t :submit_and_view%></a>
  </div>
</div>