config/routes.rb
Rails.application.routes.draw do

  resources :blogs
  resources :passengers
  devise_for :users, :controllers => {:registrations => "registrations", sessions: "sessions"}
  resources :agencies
  resources :tour_packages
  resources :tours
  resources :uploads
  resources :blogs
  resources :access_controls


  get '', to: 'home#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root "home#index"

  get 'settings/index'
  get "settings/sections" => "settings#sections"
  get '/settings', to: "settings#index"

  post '/airlines', to: "airlines#create"
  post '/railways', to: "railways#create"
  post '/buses', to: "buses#create"
  post '/hotels', to: "hotels#create"
  post '/price_types', to: "price_types#create"

  get '/uploads/remoted/:id', to: "uploads#remoted"
  get '/tour_packages/upload/:id', to: "tour_packages#upload"

  get '/railways/options', to: "railways#options"
  get '/airlines/options', to: "airlines#options"
  get '/buses/options', to: "buses#options"

  get '/reservations/new', to: "reservations#new"
  get '/reservations/passengers', to: "reservations#passengers"
  get '/reservations/verification', to: "reservations#verification"
  get '/reservations/:id/destroy', to: "reservations#destroy"
  get '/reservations/verify_reservations/:id', to: "reservations#verify_reservations"


  get '/tour_packages/check/:id', to: "tour_packages#check"
  get '/tour_packages/change_rank/:id', to: "tour_packages#change_rank"
  get '/tour_packages/change_status/:id', to: "tour_packages#change_status"

  get '/blogs/check/:id', to: "blogs#check"
  get '/blogs/change_rank/:id', to: "blogs#change_rank"

  get '/landing', to: "home#landing"

  post '/roles', to: "roles#create"
  get '/roles/:id/destroy', to: "roles#destroy"
  get '/roles/access/:id', to: "roles#access"
  get '/roles/change_current_role', to: "roles#change_current_role"

  post '/assignments', to: "assignments#create"
  get '/assignments/:id/destroy', to: "assignments#destroy"

  post '/provinces', to: "provinces#create"
  get '/provinces/:id/destroy', to: "provinces#destroy"

  get '/api/tour_packages', to: "api#tour_packages"
  get '/api/tour_package/:id', to: "api#tour_package"
  get '/api/tour/:id', to: "api#tour"
  get '/api/login', to: "api#login"
  get '/api/tour_reservations/:id', to: "api#tour_reservations"
  get '/api/delete_reservation/:id', to: "api#delete_reservation"
  get '/api/verify_reservation/:id', to: "api#verify_reservation"
  get '/api/verified_reservations/:id', to: "api#verified_reservations"
  get '/api/my_reservations', to: "api#my_reservations"
  get '/api/blogs', to: "api#blogs"
  get '/api/provinces', to: "api#provinces"
  get '/api/blog/:id', to: "api#blog"

  post '/api/sign_up', to: "api#sign_up"
  post '/api/reservation', to: "api#reservation"
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  validates :name, presence: true
  validates_format_of :subdomain, :with =>  /\A[a-zA-Z0-9]*\z/

  belongs_to :user
  has_many :tour_packages, :dependent => :destroy

  before_create :set_uuid
  def set_uuid
    self.uuid = SecureRandom.uuid
  end

  def id
    self.uuid
  end

  def self.find(uuid)
    Agency.find_by_uuid(uuid)
  end
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    if current_user.agency.blank?
      @agency = Agency.new
    else
      redirect_to "/agencies/#{current_user.agency.id}/edit"
    end
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)
    @agency.user_id = current_user.id
    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    @agency.user_id = current_user.id
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:name, :tel, :telegram_channel, :instagram_page, :address, :subdomain, :mobile, :fax, :email, :about_us)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= form_for(@agency, html: {class: 'card'}) do |f| %>
<div class="card-header">
  <h3 class="card-title"><%=t :agency_form %></h3>
</div>
<% if @agency.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

  <ul>
    <% @agency.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="card-body">
  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :subdomain, class: "form-label" %>
        <%= f.text_field :subdomain , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :tel, class: "form-label" %>
        <div class="input-group">
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fa fa-phone" aria-hidden="true"></i></span>
          </span>
          <%= f.text_field :tel, class: "form-control", placeholder: "", style: 'direction: ltr;' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :mobile, class: "form-label" %>
        <div class="input-group">
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fa fa-tablet" aria-hidden="true"></i></span>
          </span>
          <%= f.text_field :mobile, class: "form-control", placeholder: "", style: 'direction: ltr;' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :fax, class: "form-label" %>
        <div class="input-group">
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fa fa-fax" aria-hidden="true"></i></span>
          </span>
          <%= f.text_field :fax , class: "form-control", placeholder: "" , style: 'direction: ltr;'%>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :telegram_channel, class: "form-label" %>
        <div class="input-group">
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fab fa-telegram"></i></span>
          </span>
          <%= f.text_field :telegram_channel , class: "form-control", placeholder: "" , style: 'direction: ltr;'%>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :instagram_page, class: "form-label" %>
        <div class="input-group">
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text"><i class="fab fa-instagram"></i></span>
          </span>
          <%= f.text_field :instagram_page , class: "form-control", placeholder: "", style: 'direction: ltr;' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :email, class: "form-label" %>
        <div class="input-group">
          <span class="input-group-prepend" id="basic-addon1">
            <span class="input-group-text">@</span>
          </span>
          <%= f.text_field :email , class: "form-control", placeholder: "", style: 'direction: ltr;' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :address, class: "form-label" %>
        <%= f.text_area :address , class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :about_us, class: "form-label" %>
        <%= f.text_area :about_us , class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="card-footer text-right">
    <button type="submit" class="btn btn-primary"><%=t :submit%></button>
  </div>
</div>
<% end %>

app/views/agencies/index.html.erb
<div class="row row-cards">
  <div class="col-lg-3">
    <div class="row">
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-12">
        <div class="card">
          <div class="card-body">

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="card">
      <table class="table card-table table-vcenter">
        <tbody>
          <% @agencies.each do |agency| %>
          <tr>
                        <td><%= agency.name %></td>
                        <td><%= agency.tel %></td>
                        <td><%= agency.telegram_channel %></td>
                        <td><%= agency.instagram_page %></td>
                        <td><%= agency.address %></td>
                        <td><%= agency.uuid %></td>
                        <td><%= agency.user_id %></td>
                        <td><%= agency.subdomain %></td>
                        <td><%= agency.mobile %></td>
                        <td><%= agency.fax %></td>
                        <td><%= agency.email %></td>
                        <td><%= agency.about_us %></td>
                        <td><%= link_to t(:show), agency %></td>
            <td><%= link_to t(:edit), edit_agency_path(agency) %></td>
            <td><%= link_to t(:destroy), agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/agencies/show.html.erb
<div class='row'>
  <div class="col-lg-4 order-lg-1">
  </div>
  <div class="col-lg-8 order-lg-1">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"></h3>
        <div class="card-options">
          <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
        </div>
      </div>
      <div class="card-body">
        <div class='row'>
          <div class='col-md-12 col-lg-12'>
                        <div class="form-group">
              <%= label :agency, :name , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.name %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :tel , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.tel %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :telegram_channel , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.telegram_channel %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :instagram_page , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.instagram_page %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :address , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.address %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :uuid , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.uuid %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :user_id , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.user_id %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :subdomain , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.subdomain %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :mobile , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.mobile %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :fax , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.fax %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :email , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.email %></div>
            </div>
                        <div class="form-group">
              <%= label :agency, :about_us , class: "form-label", style: 'color: #7795c1;'%>              <div class="form-control-plaintext"><%= @agency.about_us %></div>
            </div>
                      </div>
        </div>
      </div>
    </div>
  </div>
</div>